PL.MVC/Models/Post/ChangePostModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace PL.MVC.Models.Post
{
    public class ChangePostModel
    {
        [HiddenInput(DisplayValue = false)]
        public Guid Id { get; set; }

        [StringLength(512, ErrorMessage = "Maximum length is {1} characters.")]
        [UIHint("Multilinetext")]
        public string Description { get; set; }
    }
}

PL.MVC/Models/Post/CreatePostModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Web;
using System.Web.Mvc;

namespace PL.MVC.Models.Post
{
    public class CreatePostModel
    {
        [HiddenInput(DisplayValue = false)]
        public Guid AuthorId { get; set; }

        [StringLength(512, ErrorMessage = "Maximum length is {1} characters.")]
        [UIHint("Multilinetext")]
        public string Description { get; set; }

        [Required]
        [Display(Name = "Photo")]
        public HttpPostedFileBase Photo { get; set; }

    }
}

PL.MVC/Models/Post/PostViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using PL.MVC.Models.Like;
using PL.MVC.Models.User;

namespace PL.MVC.Models.Post
{
    public class PostViewModel
    {
        [HiddenInput(DisplayValue = false)]
        public Guid Id { get; set; }

        public UserViewModel Author { get; set; }

        public string Description { get; set; }

        [UIHint("DateTimeView")]
        public DateTime CreateDate { get; set; }

        public List<ViewLikeModel> Likes { get; set; } 
    }
}

PL.MVC/Controllers/LikeController.cs
using System;
using System.Web.Mvc;
using AutoMapper;
using BLL.Interface.Entities;
using BLL.Interface.Services;
using PL.MVC.Models.Like;

namespace PL.MVC.Controllers
{
    [Authorize]
    public class LikeController : Controller
    {
        private readonly IUserService _userService ;
        private readonly ILikeService _likeService;

        public LikeController(IUserService userService, ILikeService likeService)
        {
            _likeService = likeService;
            _userService = userService;
        }

        public ActionResult Create(Guid id)
        {
            try
            {
                var like = new CreateLikeModel
                {
                    PostId = id,
                    UserId = GetUserId()
                };

                var bllLike = Mapper.Map<BllLike>(like);
                bllLike.CreateDate = DateTime.Now;
                _likeService.Create(bllLike);
            }
            catch (Exception)
            {

            }
            return PartialView("_DeleteLike", id);
        }

        public ActionResult Delete(Guid id)
        {
            try
            {
                _likeService.Delete(id, GetUserId());
            }
            catch (Exception)
            {
                
                throw;
            }
            
            return PartialView("_CreateLike", id);
        }


        [ChildActionOnly]
        public ActionResult Like(Guid id)
        {
            return PartialView("_CreateLike", id);
        }

        [ChildActionOnly]
        public ActionResult UnLike(Guid id)
        {
            return PartialView("_DeleteLike", id);
        }

        private Guid GetUserId()
        {
            return _userService.GetByUserName(HttpContext.User.Identity.Name).Id;
        }

    }
}

PL.MVC/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using BLL.Interface.Entities;
using BLL.Interface.Services;
using PL.MVC.Infrastructure;
using PL.MVC.Models.Post;

namespace PL.MVC.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private readonly IService<BllPostPhoto> _photoService;
        private readonly IService<BllPost> _postService;
        private readonly IUserService _userService;

        public PostController(IService<BllPostPhoto> photoService, IService<BllPost> postService, IUserService userService)
        {
            _photoService = photoService;
            _postService = postService;
            _userService = userService;
        }

        public FileContentResult Photo(Guid id)
        {
            var photo = _photoService.GetById(id);
            if (photo != null)
            {
                return File(photo.Photo, photo.PhotoType);
            }
            else
            {
                return null;
            }
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreatePostModel newPost)
        {
            if (ModelState.IsValid)
            {
                var currentUser = _userService.GetByUserName(HttpContext.User.Identity.Name);
                newPost.AuthorId = currentUser.Id;
                var newBllPost = Mapper.Map<BllPost>(newPost);
                newBllPost.CreateDate = DateTime.Now;
                var newPostId = _postService.Create(newBllPost);
                AddPhoto(newPostId, newPost.Photo);
                return RedirectToActionPermanent("Profile", "Home", new {id = currentUser.UserName});
            }

            return View(newPost);
        }

        public string Delete(Guid id)
        {
            if (CheckUser(id))
            {
                _photoService.Delete(id);
                _postService.Delete(id);
                return "Post deleted is.";
            }
            else
            {
                return "error";
            }
        }

        public ActionResult Change(Guid id)
        {
            if (CheckUser(id))
            {
                var post = _postService.GetById(id);
                return PartialView("_Change", new ChangePostModel {Id = post.Id, Description = post.Description});
            }
            return null;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Change(ChangePostModel post)
        {
            if (ModelState.IsValid)
            {
                var changePost = _postService.GetById(post.Id);
                changePost.Description = post.Description;
                changePost.AuthorId = changePost.Author.Id;
                _postService.Update(changePost);
                return PartialView("_PostRoot", Mapper.Map<PostViewModel>(changePost));
            }

            return PartialView("_Change", post);
        }

        public ActionResult ChangeCancel(Guid id)
        {
            var post = _postService.GetById(id);
            return PartialView("_PostRoot", Mapper.Map<PostViewModel>(post));
        }

        public ActionResult UserList(Guid id, int page = 1)
        {
            var blockInfo = new UserBlockInfo<PostViewModel>
            {
                PageSize = 5,
                PageNumber = page,
                TotalItems = _postService.Count(post => post.AuthorId == id),
                UserId = id
            };
            var items = _postService.GetByPredicate(post => post.AuthorId == id, post => post.CreateDate, blockInfo.Skip,
                blockInfo.PageSize);
            blockInfo.Items = Mapper.Map<IEnumerable<PostViewModel>>(items);
            return PartialView("_UserBlock", blockInfo);
        }

        public ActionResult Main(int page = 1)
        {
            var userId = GetCurrentUserId();
            var blockInfo = new BlockInfo<PostViewModel>
            {
                PageSize = 5,
                PageNumber = page,
                TotalItems = _postService.Count(post => post.AuthorId != userId)
            };
            var items = _postService.GetByPredicate(post => post.AuthorId != userId, post => post.CreateDate,
                blockInfo.Skip, blockInfo.PageSize);
            blockInfo.Items = Mapper.Map<IEnumerable<PostViewModel>>(items);
            return PartialView("_IndexBlock", blockInfo);
        }

        public ActionResult Search(string search, int page = 1)
        {
            var userId = GetCurrentUserId();
            var blockInfo = new SearchBlockInfo<PostViewModel>
            {
                PageSize = 5,
                PageNumber = page,
                SearchString = search,
                TotalItems = _postService.Count(post => post.Description.Contains(search) && post.AuthorId != userId)
            };
            var items = _postService.GetByPredicate(post => post.Description.Contains(search) && post.AuthorId != userId,
                post => post.CreateDate, blockInfo.Skip, blockInfo.PageSize);
            blockInfo.Items = Mapper.Map<IEnumerable<PostViewModel>>(items);
            return PartialView("_SearchBlock", blockInfo);
        }

        private void AddPhoto(Guid id, HttpPostedFileBase image)
        {
            var photo = new BllPostPhoto();
            photo.Id = id;
            photo.Photo = new byte[image.ContentLength];
            image.InputStream.Read(photo.Photo, 0, image.ContentLength);
            photo.PhotoType = image.ContentType;
            _photoService.Create(photo);
        }

        private bool CheckUser(Guid postId)
        {
            var post = _postService.GetById(postId);

            if (post.Author.UserName.Equals(HttpContext.User.Identity.Name, StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
            return false;
        }

        private Guid GetCurrentUserId()
        {
            return _userService.GetByUserName(HttpContext.User.Identity.Name).Id;
        }
    }
}

PL.MVC/Controllers/UserController.cs
using System;
using System.IO;
using System.Web.Mvc;
using BLL.Interface.Services;
using BLL.Interface.Entities;

namespace PL.MVC.Controllers
{
    public class UserController : Controller
    {
        private const string DefaultAvatarPath = "~/Content/images/default-avatar.jpg";
        private const string DefaultAvatarType = "image/jpeg";

        private readonly IUserService _userService;
        private readonly IService<BllAvatar> _avatarService;
 
        public UserController (IUserService userService, IService<BllAvatar> avatarServise)
        {
            _userService = userService;
            _avatarService = avatarServise;
        }

        public FileContentResult Avatar(Guid id)
        {
            var avatar = _avatarService.GetById(id);
            if (avatar != null)
            {
                return File(avatar.Image, avatar.MineType);
            }
            else
            {
                string path = HttpContext.Server.MapPath(DefaultAvatarPath);
                if (System.IO.File.Exists(path))
                {
                    using(var reader = new BinaryReader(new FileStream(path, FileMode.Open)))
                    {
                        var image = reader.ReadBytes((int)reader.BaseStream.Length);
                        return File(image, DefaultAvatarType);
                    }
                }
                else
                {
                    return null;
                }
            }
        }
    }
}

PL.MVC/Views/Post/Create.cshtml
@model PL.MVC.Models.Post.CreatePostModel

@{
    ViewBag.Title = "Create post";
}

<h2>Create post</h2>

@using (Html.BeginForm("Create", "Post", FormMethod.Post, new { id = "post-create", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div>
        @Html.LabelFor(model => model.Photo)<br>
        @Html.EditorFor(model => model.Photo)
        @Html.ValidationMessageFor(model => model.Photo)<br>

        @Html.LabelFor(model => model.Description)<br>
        @Html.EditorFor(model => model.Description)
        @Html.ValidationMessageFor(model => model.Description)<br>

        <input type="submit" value="Submit"/>
    </div>
}

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $.validator.addMethod('accept', function () { return true; });
    </script>
}

PL.MVC/Views/Post/_Change.cshtml
@model PL.MVC.Models.Post.ChangePostModel

@using (Ajax.BeginForm("Change", null, new AjaxOptions { UpdateTargetId = "root-" + Model.Id }, new { @class = "form-group" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    
    <div class="label-for">
        @Html.EditorFor(model => model.Id)
    </div>

    
    @Html.LabelFor(model=>model.Description)

    <div class="editor-for">
        @Html.TextAreaFor(model => model.Description, new {@class = "form-control", rows = "5"})
    </div>
    
    @Html.ValidationMessageFor(model => model.Description)

    <input type="submit" value="Save" class="btn btn-info btn-sm"/>
    <a class="btn btn-default btn-sm" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#root-@Model.Id.ToString()"
        href=@Url.Action("ChangeCancel", "Post", new {id = Model.Id}) >Cancel</a>
}

PL.MVC/Views/Post/_IndexBlock.cshtml
@model PL.MVC.Infrastructure.BlockInfo<PL.MVC.Models.Post.PostViewModel>

@Html.Partial("_List", Model.Items)

@if (Model.CurrentItems < Model.TotalItems)
{
    <div id="block-@Model.PageNumber">
        <ul class="pager">
            <li><a data-ajax="true" data-ajax-mode="replace" data-ajax-update="#block-@Model.PageNumber" href=@Url.Action("Main", "Post", new {page = ++Model.PageNumber})>
                    Load more
                </a>
            </li>
        </ul>
    </div>
}

PL.MVC/Views/Post/_List.cshtml
@model IEnumerable<PL.MVC.Models.Post.PostViewModel>

@foreach (var post in Model)
{     
        @Html.Partial("_Post", post)
}

PL.MVC/Views/Post/_Post.cshtml
@model PL.MVC.Models.Post.PostViewModel

<article id="@Model.Id.ToString()" class="row post">
    <header class="post-header">
        <img class="owner-avatar img-circle" src="@Url.Action("Avatar", "User", new {id = Model.Author.Id})"/>
        <div class="owner-location">
            @Html.ActionLink(Model.Author.UserName, "Profile", "Home", new {id = Model.Author.UserName}, new {@class = "user-link"})
        </div>
        @Html.TimeStamp(Model.CreateDate)
    </header>
    <div class="post-photo-root">
        <div class="post-photo-placeholder">
            <img class="post-photo" src="@Url.Action("Photo", new {id = Model.Id})"/>
        </div>
    </div>
    <div class="post-root" id="root-@Model.Id.ToString()">
        @Html.Partial("_PostRoot")
    </div>
</article>

PL.MVC/Views/Post/_PostRoot.cshtml
@model PL.MVC.Models.Post.PostViewModel

@{
    var userLike = Model.Likes.SingleOrDefault(like => like.UserName.Equals(HttpContext.Current.User.Identity.Name, StringComparison.OrdinalIgnoreCase));
    if (userLike != null)
    {
        Model.Likes.Remove(userLike);
    }
    Model.Likes.Sort((a, b) => b.CreateDate.CompareTo(a.CreateDate));
}

@Html.PostLikes(Model.Likes)
<h1 class="post-description"> @Model.Description</h1>
<section class="post-feedback">
    <div class="row vertical-align">
        <div id="like-@Model.Id.ToString()" class="col-lg-2 text-left">
            @{ var updateId = "#like-" + Model.Id.ToString(); }
            @if (userLike == null)
            {
                <a data-ajax="true" data-ajax-mode="replace" data-ajax-update="@updateId" href=@Url.Action("Create", "Like", new {id = Model.Id})>
                    <span class="glyphicon glyphicon-heart-empty post-like gi-2x gi-gray"></span> 
                </a>
            }
            else
            {
                <a data-ajax="true" data-ajax-mode="replace" data-ajax-update="@updateId" href=@Url.Action("Delete", "Like", new {id = Model.Id})>
                    <span class="glyphicon glyphicon-heart post-like gi-red gi-2x"></span> 
                </a>
            }
        </div>
        @if (Model.Author.UserName.Equals(HttpContext.Current.User.Identity.Name, StringComparison.OrdinalIgnoreCase))
        {
            <div class="vertical-align div-right">
                <a data-ajax="true" class="post-feedback-link" data-ajax-mode="replace" data-ajax-update="#root-@Model.Id.ToString()" href=@Url.Action("Change", "Post", new {id = Model.Id})>
                    <span class="glyphicon glyphicon-pencil post-like gi-2x gi-gray"></span> 
                </a>
                <a data-ajax="true" class="post-feedback-link" data-ajax-mode="replace" data-ajax-confirm="Are you sure?" data-ajax-update="#@Model.Id.ToString()" href=@Url.Action("Delete", "Post", new {id = Model.Id})>
                    <span class="glyphicon glyphicon-remove-circle gi-2x gi-gray"></span> 
                </a>
            </div>
        }
    </div>
</section>

PL.MVC/Views/Post/_SearchBlock.cshtml
@model PL.MVC.Infrastructure.SearchBlockInfo<PL.MVC.Models.Post.PostViewModel>

@Html.Partial("_List", Model.Items)

@if (Model.CurrentItems < Model.TotalItems)
{
    <div id="block-@Model.PageNumber">
        @Ajax.ActionLink("Upload more.", "Search", "Post", 
            new {search = Model.SearchString, page = Model.PageNumber + 1}, new AjaxOptions{UpdateTargetId = "block-"+@Model.PageNumber} )


    </div>
}

PL.MVC/Views/Post/_UpdateDescription.cshtml
@model PL.MVC.Models.Post.ChangePostModel

@Model.Description
<div>
    @Ajax.ActionLink("Change", "Change", new {id = Model.Id}, new AjaxOptions {UpdateTargetId ="description-" + Model.Id.ToString()})
    @Ajax.ActionLink("Delete", "Delete", new {id = Model.Id}, new AjaxOptions{UpdateTargetId = Model.Id.ToString(), Confirm = "Are you sure?"} )
</div>

PL.MVC/Views/Post/_UserBlock.cshtml
@model PL.MVC.Infrastructure.UserBlockInfo<PL.MVC.Models.Post.PostViewModel>

@Html.Partial("_List", Model.Items)

@if (Model.CurrentItems < Model.TotalItems)
{
    <div id="block-@Model.PageNumber">
        @Ajax.ActionLink("Upload more.", "UserList", "Post", 
            new {id = Model.UserId, page = Model.PageNumber + 1}, new AjaxOptions{UpdateTargetId = "block-"+@Model.PageNumber} )
    </div>
}